Add e2e tests
UniqueNetwork/unique-sdk pull request #324
Opened 2022-09-05 14:52 UTC by Degtiv

Please check e2e tests for sdk client

2022-10-10 09:48 UTC, AnnaNX1 commented on e2e/package.json
> +    "@unique-nft/accounts": "file:../packages/accounts",
Судя по пути, подключаются не собранные пакеты, может имеет смысл собранные пакеты подключать?

2022-10-10 09:56 UTC, AnnaNX1 commented on e2e/test/straight-flow.test.ts
> +    const normalized = UniqueUtils.Address.normalize.substrateAddress(secondAddress, prefix);
Вместо import { UniqueUtils } from '@unique-nft/api'; теперь надо использовать import { Address } from '@unique-nft/utils';

2022-10-10 10:20 UTC, AnnaNX1 approved these changes

2022-10-10 10:24 UTC, Degtiv commented on e2e/package.json
> +    "@unique-nft/accounts": "file:../packages/accounts",
смысл как раз в том, чтобы проводить тестирование перед тем как пакет будет выложен. В идеале - перед мерджем новых фичей тонкого клиента в мастер

2022-10-10 13:51 UTC, ashkuc commented
> ### DO NOT MERGE!
> Very early version of e2e tests.

may be mark as draft?

2022-10-10 13:55 UTC, Degtiv commented
> > ### DO NOT MERGE!
> > Very early version of e2e tests.
> 
> may be mark as draft?

This old message is no longer relevant. The PR was a draft, but not now.

2022-10-17 17:19 UTC, ashkuc commented on e2e/package.json
> +    "test": "mocha --timeout 500000 --exit -r ts-node/register './test/*.test.ts' -R mochawesome"
+ надо починить lock файл, `npm ci` ругается

2022-10-17 17:20 UTC, ashkuc approved these changes

2022-10-18 07:11 UTC, alexsharypin approved these changes

2022-10-18 11:57 UTC, Degtiv commented on e2e/package.json
> +    "test": "mocha --timeout 500000 --exit -r ts-node/register './test/*.test.ts' -R mochawesome"
> * надо починить lock файл, `npm ci` ругается

Для проекта e2e 'npm ci' не выдаёт ошибки:
![image](https://user-images.githubusercontent.com/35498858/196422999-01da9372-d524-4ff2-a76b-5b5f2f6bde50.png)

2022-10-20 02:56 UTC, overpod requested changes

2022-10-20 02:56 UTC, overpod commented on e2e/test/straight-flow.test.ts
> +    console.log(JSON.stringify(result, null, 2));
console.log здесь нужен ?

2022-10-20 02:56 UTC, overpod commented on e2e/utils/collections.ts
> +  console.log('result:');
тут вывод результата точно нужен ?

2022-10-20 06:37 UTC, Degtiv commented on e2e/utils/collections.ts
> +  console.log('result:');
точно не нужен :)

2022-10-20 06:37 UTC, Degtiv commented on e2e/test/straight-flow.test.ts
> +    console.log(JSON.stringify(result, null, 2));
не нужен

2022-10-20 07:27 UTC, overpod requested changes

2022-10-20 07:27 UTC, overpod commented on e2e/test/properties.test.ts
> +    console.log(JSON.stringify(propPermission, null, 2));
Мне кажется тут лишний console.log

2022-10-21 08:35 UTC, overpod approved these changes

2022-10-21 08:41 UTC, merged