Solidity errors
UniqueNetwork/unique-sdk pull request #425
Opened 2022-10-17 08:33 UTC by abdulgalimov

2022-10-17 08:55 UTC, pasynkov approved these changes

2022-10-17 09:26 UTC, overpod requested changes

2022-10-17 09:26 UTC, overpod commented on packages/substrate-client/evm/methods/call/errors.ts
> +import * as console from 'console';
эту строчку можно убрать

2022-10-18 07:46 UTC, abdulgalimov commented on packages/substrate-client/evm/methods/call/errors.ts
> +import * as console from 'console';
done )

2022-10-19 07:40 UTC, merged