add state-query module in SDK
UniqueNetwork/unique-sdk pull request #450
Opened 2022-10-25 13:49 UTC by abdulgalimov

2022-10-26 08:26 UTC, pasynkov commented on packages/sdk/src/index.ts
> +        console.log('exception', exception);
опа чирик

2022-10-26 09:06 UTC, abdulgalimov commented on packages/sdk/src/index.ts
> +        console.log('exception', exception);
выдавил

2022-10-27 09:24 UTC, overpod requested changes

2022-10-27 09:24 UTC, overpod commented on packages/sdk/src/testing/state-query.spec.ts
> +    createArgs = {
createArgs не используется в тесте ну и richAccountAddress тоже

2022-10-27 10:35 UTC, abdulgalimov commented on packages/sdk/src/testing/state-query.spec.ts
> +    createArgs = {
done

2022-10-27 11:32 UTC, overpod approved these changes

2022-10-27 11:46 UTC, abdulgalimov commented on packages/sdk/src/types/interfaces.ts
> +export interface IStateQueries {
done

2022-10-27 13:11 UTC, alexsharypin approved these changes

2022-10-27 13:12 UTC, merged