[SDK-478] Add IPFS multiple-files-upload to SDK
UniqueNetwork/unique-sdk pull request #483
Opened 2022-11-07 15:18 UTC by ashkuc

2022-11-07 15:22 UTC, pasynkov commented on packages/rest/src/app/modules/ipfs/README.md
> +curl -v -F file=@./1.jpg https://rest.dev.uniquenetwork.dev/v1/ipfs/upload-file
атата, линтер же где то был?

2022-11-07 16:02 UTC, ashkuc commented on packages/rest/src/app/modules/ipfs/README.md
> +curl -v -F file=@./1.jpg https://rest.dev.uniquenetwork.dev/v1/ipfs/upload-file
а линтер на что, это же ридми?
Заменил ссылки

2022-11-08 07:18 UTC, overpod requested changes

2022-11-08 07:18 UTC, overpod commented on packages/sdk/src/testing/page/src/components/upload-multiple-files.js
> +    console.log(result);
можно убрать ```console.log(result);```

2022-11-08 07:18 UTC, overpod commented on packages/sdk/src/testing/page/src/components/upload-multiple-files.js
> +  const [existingDirCid, setExistingDirCid] = useState('');
existingDirCid вроде нигде не мутирует.
setExistingDirCid не используется.

2022-11-08 07:18 UTC, overpod commented on packages/sdk/src/testing/script/index.cjs
> +    console.log(JSON.stringify({ firstUrl, secondUrl }, null, 2));
```console.log``` точно нужен ?

2022-11-08 07:18 UTC, overpod commented on packages/sdk/src/testing/script/index.cjs
> +    console.error(error);
```console.log``` точно нужен ?

2022-11-08 08:34 UTC, ashkuc commented on packages/sdk/src/testing/script/index.cjs
> +    console.log(JSON.stringify({ firstUrl, secondUrl }, null, 2));
но это же просто пример

2022-11-08 08:34 UTC, ashkuc commented on packages/sdk/src/testing/script/index.cjs
> +    console.error(error);
это просто пример и проверка работы

2022-11-08 08:35 UTC, ashkuc commented on packages/sdk/src/testing/script/index.cjs
> +    console.error(error);
это cjs файл, как мне ещё выводить инфу, сразу в stdout ?

2022-11-08 08:37 UTC, abdulgalimov approved these changes

2022-11-08 08:58 UTC, AnnaNX1 commented on packages/rest/src/app/modules/ipfs/README.md
> +const name = 'punk-1.png';
константа name не используется

2022-11-08 08:59 UTC, AnnaNX1 approved these changes

2022-11-08 13:10 UTC, merged