SDK-484 Added getFee method in mutation
UniqueNetwork/unique-sdk pull request #504
Opened 2022-11-11 06:27 UTC by overpod

2022-11-11 07:33 UTC, abdulgalimov commented on packages/rest/src/app/modules/mutation/mutation.service.ts
> +      throw new BuildError(
Можно оставить возможность передавать в метод GetFee массив объектов, чтобы получился batching fee. Т.е. если массив, тогда надо пройтись по нему, посчитать все fee и сложить их.

2022-11-11 07:36 UTC, abdulgalimov commented on packages/rest/src/app/modules/mutation/mutation.service.ts
>      const fee = withFee ? await method.getFee(args) : undefined;
Вот это надо выпилить, но не сейчас, а чуть позже. А сейчас наверно надо как то поменить что поле withFee в запрое `deprecated`.

2022-11-14 09:38 UTC, abdulgalimov commented on packages/rest/src/app/modules/mutation/mutation.service.ts
> +      argsList.map((arg) => method.getFee(arg)),
getFee же Promise возвращает

2022-11-14 09:41 UTC, abdulgalimov commented on packages/rest/src/app/modules/mutation/mutation.service.ts
> +      argsList.map((arg) => method.getFee(arg)),
а все понял, вопрос снимается )

2022-11-14 09:44 UTC, abdulgalimov requested changes
Надо в SDK метод Mutation::getFee переделать на новый use=GetFee, там сейчас запрашивается с помощью параметра withFee.

2022-11-14 21:53 UTC, abdulgalimov commented on packages/rest/src/app/modules/mutation/mutation.service.ts
> +    fee: Balance;
Здесь надо сделать новый Интерфейс, чтобы потом можно было прогнать генерацию типов для SDK и там же в SDK указать правильный тип для метода getFee

2022-11-15 08:37 UTC, abdulgalimov commented on packages/sdk/src/common/mutation.ts
>    ): Promise<FeeResponse> {
здесь FeeBodyResponse. И внутри в FeeBodyResponse поле fee помечено как не обязательное, надо сделать его обязательным.

2022-11-16 09:24 UTC, abdulgalimov approved these changes

2022-11-18 08:45 UTC, pasynkov approved these changes

2022-11-18 09:17 UTC, ashkuc approved these changes

2022-11-21 09:57 UTC, merged