Substrate-client subscriptions
UniqueNetwork/unique-sdk pull request #520
Opened 2022-11-16 15:21 UTC by abdulgalimov

2022-11-21 12:27 UTC, overpod requested changes

2022-11-21 12:27 UTC, overpod commented on packages/substrate-client/subscriptions/subscriptions.spec.ts
> +        console.log(
тут наверное нужно тестировать наличие полей в signedBlock.

2022-11-21 12:48 UTC, abdulgalimov commented on packages/substrate-client/evm/utils.ts
> +  logs: EventRecord[],
done

2022-11-21 12:48 UTC, abdulgalimov commented on packages/substrate-client/src/lib/methods-store.ts
> +      const errorMessage = `[MethodsStore] Duplicate mutation ${call.section}x-${call.method} methods ${current?.constructor.name} -> ${method.constructor.name}`;
опечатка, убрал

2022-11-21 12:48 UTC, abdulgalimov commented on packages/substrate-client/subscriptions/observables/extrinsics.ts
> +  client: Client,
убрал

2022-11-21 12:48 UTC, abdulgalimov commented on packages/substrate-client/subscriptions/subscriptions.spec.ts
> +        console.log(
done

2022-11-21 12:53 UTC, overpod approved these changes

2022-11-22 13:41 UTC, ashkuc approved these changes

2022-11-25 12:15 UTC, alexsharypin approved these changes

2022-11-25 12:58 UTC, merged