Add validate
UniqueNetwork/unique-sdk pull request #56
Opened 2022-05-25 15:33 UTC by AnnaNX1

2022-05-26 06:46 UTC, ashkuc commented on packages/web/src/app/types/sdk-methods.ts
> +  @NotEquals(0)
Скорее @IsPositive()

https://github.com/typestack/class-validator#validation-decorators

2022-05-26 06:46 UTC, ashkuc commented on packages/web/src/app/types/sdk-methods.ts
> +  @NotEquals(0)
Скорее @IsPositive()

https://github.com/typestack/class-validator#validation-decorators

2022-05-30 07:54 UTC, abdulgalimov commented on packages/web/tests/collection.spec.ts
> +    it.each(['foo', -1, 1.1])('invalid collectionId', async (collectionId) => {
Здесь в имени тест лучше использовать переменные:
`invalid collectionId - %s`
чтобы при просмотре тестов было видно какие запустились и какие отвалились.

2022-05-30 08:02 UTC, AnnaNX1 commented on packages/web/src/app/types/sdk-methods.ts
> +  @NotEquals(0)
Исправила

2022-06-01 09:02 UTC, ashkuc requested changes

2022-06-01 09:02 UTC, ashkuc commented on packages/web/src/app/controllers/token.controller.ts
> +  @UsePipes(new CustomValidationPipe({}))
Если эта Pipe используется на каждом методе контроллера, то проще повесить её просто сразу на контроллер
@UsePipes вроде бы это поддерживает

https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/use-pipes.decorator.ts#L11

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/tests/collection.spec.ts
> +      const { ok, body } = await request(app.getHttpServer())
body можно удалить, инспекция светится

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/tests/collection.spec.ts
> +      const { ok, body } = await request(app.getHttpServer())
body можно удалить, инспекция светится

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/tests/token.spec.ts
> +      const { ok, body } = await request(app.getHttpServer())
body можно удалить, инспекция светится

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/tests/token.spec.ts
> +        generatedCollection = body;
generatedCollection тоже можно удалить, потому что не используется

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/src/app/types/sdk-methods.ts
> +  NotEquals,
Не используется, можно удалить

2022-06-01 09:29 UTC, abdulgalimov commented on packages/web/src/app/validation/src/validation.pipe.ts
> +  implements PipeTransform<any>
`<any>` наверно можно убрать, оставить просто:
```js
implements PipeTransform
```

2022-06-01 09:31 UTC, abdulgalimov commented on packages/web/src/app/validation/src/validation.pipe.ts
> +  implements PipeTransform<any>
Можно  в классе  `ExtrinsicsController` удалить использование `validate` в методе `submitTx`, и тогда выглядит так, что файл 
```
packages/web/src/app/validation/src/validate.ts
```
можно вообще выпилить из проекта

2022-06-01 12:57 UTC, AnnaNX1 commented on packages/web/tests/token.spec.ts
> +        generatedCollection = body;
generatedCollection используется, из него берутся поля signerPayloadHex, signerPayloadJSON для следующих тестов

2022-06-01 13:29 UTC, AnnaNX1 commented on packages/web/src/app/validation/src/validation.pipe.ts
> +export class CustomValidationPipe
> Мне кажется что это то же самое что `export const SdkValidationPipe = new ValidationPipe({ exceptionFactory: (errors) => new ValidationError(errors) });`

Что-то не получилось(

2022-06-01 14:10 UTC, ashkuc approved these changes

2022-06-01 14:10 UTC, merged